WebServer:
  Address: 0.0.0.0
  Port: 8080

Jwt:
  JwtSecret: '${SERVER_JWT_SECRET}'
  JwtExpireHour: 12

Redis:
  Db: 0
  Address: '${SERVER_REDIS_ADDRESS}'
  Password: '${SERVER_REDIS_PASSWORD}'

Database:
  Address: '${SERVER_DB_ADDRESS}'
  Port: 5432
  User: '${SERVER_DB_USER}'
  Password: '${SERVER_DB_PASSWORD}'
  Database: '${SERVER_DB_NAME}'
  Prefix: 'tb_'

Development: false
